### PR TITLE
Implement semantic release

### LINKED ISSUE #279: npm-published packages should follow semver
### Expected Behavior

Scratch projects published to npm should use semver version numbers >= 1.0 so that dependents can control when to accept breaking changes.

### Actual Behavior

This repository uses "prerelease" version numbers like `0.2.0-prerelease.YYYYMMDDhhmmss` which contain no information about breaking changes.

### PR DESCRIPTION
**Pull request by cwillisf**
### Resolves

Resolves #279 

### Proposed Changes

This PR enables `semantic-release`, `commitlint` (including `git` hooks using `husky`), and `commitizen`. The CI config will now use `semantic-release` to publish new versions of the package, and `commitlint` will enforce "conventional" commit message format. `commitizen` is an optional developer convenience for interactively generating compliant commits.

### Reason for Changes

With these changes in place, the version number for this package will automatically follow semver conventions.

### Test Coverage

Tested locally and on CI, though the real test will be when we merge this into `develop` and see if the release happens correctly.

### CODE REVIEW

**Comment by adroitwhiz** [comment]
Just curious: when this hits scratch-render, will I have to rewrite all my commit messages for all my open PRs?

**Comment by adroitwhiz** [comment]
(also, as I said on the scratch-paint PR: will "refactor" commits trigger releases?)

**Comment by cwillisf** [comment]
To be honest, I'm not sure what the behavior is with pre-existing PRs. My guess is that semantic-release won't make a release unless there's at least one commit prefixed with `fix`, `feat`, etc., but I'll be curious to find out.

Going forward, I expect all commits -- well, all commits to `develop`, which mostly means all merged PRs -- will result in a release. But that's OK! Every merge to `develop` already causes a release to NPM, so this change won't change the frequency of releases. It's just that the version numbers will mean more.

**Comment by adroitwhiz** [comment]
> Going forward, I expect all commits -- well, all commits to develop, which mostly means all merged PRs -- will result in a release. But that's OK! Every merge to develop already causes a release to NPM, so this change won't change the frequency of releases. It's just that the version numbers will mean more.

My concern is more that "refactor" commits *won't* trigger releases--for instance, I don't think my scratch-storage PRs actually ended up getting released until other people made unrelated changes later.

**Comment by cwillisf** [comment]
> My concern is more that "refactor" commits _won't_ trigger releases

Ah, gotcha. Sorry I misunderstood. With that in mind I took a closer look at the `scratch-storage` build logs associated with LLK/scratch-storage#113 and LLK/scratch-storage#114 and saw this (similar but shorter for 113, of course):

```
[20:01:27] [semantic-release] › ℹ  Found 5 commits since last release
[20:01:27] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #114 from adroitwhiz/smaller-textencoder-textdecoder
Replace text-encoding package with fastestsmallesttextencoderdecoder
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: refactor: replace text-encoding polyfill
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Update CONTRIBUTING.md
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #113 from adroitwhiz/node-fetch
Remove NetsTool and nets dependency
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: refactor: remove NetsTool
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[20:01:27] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 5 commits complete: no release
[20:01:27] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[20:01:27] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

So... I guess `refactor:` commits don't trigger a release! Interesting.

Further digging reveals that breaking changes cause a major version bump (of course), `feat` causes a minor bump, and a patch bump is triggered by any of `revert`, `fix`, or `perf`.

I should probably talk this over with the rest of the team, but thinking about this... maybe the best answer is that if a release would be beneficial to the end-user, it should be considered `feat` or `fix` or `perf`. For example, the text encoder change could be considered a performance improvement in that it reduces the size of the built package. If it truly doesn't matter to the end user then I guess it doesn't need a release.

To be honest, I think I'd prefer if every change rolled a release, just so that we don't have merged-but-unreleased changes sitting for a long time. We can do that if we adjust the config, but that's the "I should probably talk this over with the rest of the team" part. Thanks for encouraging me to investigate & think this through!

**Comment by adroitwhiz** [comment]
> To be honest, I think I'd prefer if every change rolled a release, just so that we don't have merged-but-unreleased changes sitting for a long time. 

IIRC, if your testing workflow hasn't changed since last year, you'll also want to make sure that refactors get released so they get merged up the dependency chain (into `scratch-gui`/`scratch-www`) and you can test on staging that they *don't* change anything, right?

**Pull request closed without merging**
