### PR TITLE
Fix sanitization of prefixed SVG tags

### LINKED ISSUE #1320: Issues With Sprites on Older Projects
### Expected Behavior

Sprites in projects such as https://scratch.mit.edu/projects/152427657/ should work exactly as they did years ago.

### Actual Behavior

The sprites have strangely been replaced with question marks that also show up differently than they appear in the paint editor.

### Steps to Reproduce

Go to a project such as https://scratch.mit.edu/projects/152427657/.

### Operating System and Browser

Windows 10 on Chrome

**Note:** I wasn't sure if this should be in scratch-gui or scratch-paint or some other repo, but it seems to be an issue with the new paint editor, so I put it here.

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves https://github.com/LLK/scratch-paint/issues/1320

### Proposed Changes

This PR changes the SVG purification step to whitelist versions of all elements prefixed with `svg:`, which were previously being stripped.

In addition, it changes the "add sanitized value to document" step to parse the sanitized DOM using a `DOMParser` instead of setting `innerHTML`.

### Reason for Changes

Inkscape sometimes saves SVGs with an `svg:` prefix on all elements. DOMPurify does not recognized these prefixed tags and strips them out of the document, including the root element, `<svg:svg>`. This resulted in an error when calling `getBBox`, as there's nothing to call it on.

By whitelisting those prefixed elements, bounding box calculation now works properly on those SVGs.

There was another problem I ran into, which is that setting `svgSpot.innerHTML` to the sanitized document didn't parse the `<svg:svg>` element as an `SVGElement`, treating it as an unknown element instead, meaning that `SVGElement`-specific methods like `getBBox` were missing. I changed this to use a `DOMParser` to explicitly parse the SVG element as `image/svg+xml`, which ensures it will become an `SVGElement` in the DOM.

### Test Coverage

Tested manually (Firefox 82)

You can try it out yourself: [2.svg.txt](https://github.com/LLK/scratch-svg-renderer/files/5638448/2.svg.txt)

### CODE REVIEW

**Comment by fsih** [comment]
It looks like we should collate this and https://github.com/LLK/scratch-paint/blob/610736131897a453765bd98789f1e29ec2ede142/src/containers/paper-canvas.jsx#L197

**Comment by adroitwhiz** [comment]
The scratch-paint fix looks a lot more brute-force (regexes technically cannot properly parse all XML) but only applies to SVGs edited in the paint editor--applying it to *all* SVGs may result in some unexpected behavior.

**Review by fsih — CHANGES_REQUESTED** [review]
Hi @adroitwhiz, thanks so much for this fix, and sorry we've left it sitting for so long! We were looking at https://github.com/cure53/DOMPurify/issues/492#issuecomment-735379591 and we think we prefer the hooks method, given that we can avoid having a long list of tags that we have to keep in sync with DOMPurify's repo/FORBID_TAGS, and given that it might be able to avoid the innerHTML issue you were running into. Is there a reason that you preferred to use the ADD_TAGS route?

**Comment by adroitwhiz** [comment]
Cure53 recommended the hook "if [we] feel adventurous", which I took to mean that it's a somewhat janky fix and may *possibly* introduce security holes--there have been XSS attacks carried out [because of "mutations" that occur via innerHTML](https://research.securitum.com/dompurify-bypass-using-mxss/) (plus there may be a performance impact to setting `innerHTML` on every single node).

If scratch-paint requires `svg:` namespace prefixes to be stripped anyway, I may just look into a more robust way to do that here (either in `fixupSVGString` or a function which can be re-exported to the paint editor) rather than having to maintain this list of tags. I don't expect the list of SVG tags to change unless browsers decide to implement SVG 2.0, and judging from how long that's stalled, I doubt that's ever going to happen.

There may also be a way to remove the tag namespace via a hook without resorting to `innerHTML` by operating directly on the DOM node--I'll look into that too.

**Pull request closed without merging**
