### PR TITLE
Add a helper for creating SVG elements, from paper.js

### PR DESCRIPTION
**Pull request by fsih**
We create SVGs in many places, and this way we can share a SVG creating utility

### CODE REVIEW

**Review by cwillisf — COMMENTED** [review]
I like the idea of centralizing the creation of SVG elements but I'm a little worried about potential maintenance and licensing issues with this approach. Maybe @thisandagain can speak more to the potential licensing issues -- I'm not sure if it's OK to include an MIT-licensed source file from another project into this repository.

Would it be possible to do this with something like `const {SVGElement} = require('paper.js');`? That would alleviate both concerns. I'd be less happy about `const SVGElement = require('paper.js/something/SVGElement.js');` but that might be an option as well.

**Comment by fsih** [comment]
Paper.js currently doesn't export SVGElement, though it seems like in the build file there might be an option that would cause it to. I was worried about adding paper as a dep of svg-renderer, as that adds it as a dependency to a lot of repos...

I don't totally understand the licencing issue. If we aren't allowed to use a file from Paper here, why are we allowed to use a fork of the Paper library anywhere in Scratch?

**Comment by cwillisf** [comment]
> If we aren't allowed to use a file from Paper here, why are we allowed to use a fork of the Paper library anywhere in Scratch?

That's a fair question, and to be honest I'm not 100% sure that bringing `SVGElement.js` into this repository is a problem. However, as an example, I'm reasonably certain that it wouldn't be OK for us to replace the license on our fork of Paper.js (currently the MIT license) with the one we use in this repository (3-clause BSD) without the permission of the Paper.js authors -- and maybe even all Paper.js contributors!

**Comment by fsih** [comment]
Oh no, something something the mono-repo?

**Comment by fsih** [comment]
Anyway, this change isn't essential so I'm fine with dropping it

**Review by cwillisf — APPROVED** [review]
I just talked to @thisandagain and he indicated that the licenses are compatible with this sort of change, so I think we're good. Sorry for the confusion!

**Comment by fsih** [comment]
No problem, thanks! It's better to be safe and I'm glad you're aware of licensing issues.

**Pull request merged**
